name: CD
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.APP_HOST }}
          username: ${{ secrets.APP_USER }}
          key: ${{ secrets.SSH_PRIVATEKEY }}
          script: |
            cd /applications/fpfhmpexxg/public_html
            git pull
            composer update
            APP_ENV=production APP_DEBUG=false php artisan cache:clear

